### ISSUE TITLE
Better Component testing helpers

### ISSUE THREAD

**Issue by dsingleton** [alphagov/slimmer#150]
Applications often want to write tests that assert against something in a component, in test mode a component will render a test version, containing the arguments passed to it as JSON (not fetching anything from static).

Currently apps tend to do a substring match on the JSON within the component wrapper, which is a bit hacky. Ideally there would be test helpers that can assert a specific argument was passed to the component, without having to parse the JSON out of the markup in each application.

eg,

```
assert_component('title', 'context', 'foo')

```

This requires writing helpers for a set of testing frameworks, but as we standardised our rails frontends that should be easier, and at the least we could add a helper for the most common one.

Heres an example for an application implementing these helpers itself: https://github.com/alphagov/government-frontend/blob/master/test/test_helper.rb#L24-L83

It would be nice if this was re-usable in other apps.

**Comment by tijmenb** [comment]
Frontend uses:

```
assert page.has_selector?(shared_component_selector('beta_label'))
```

**Comment by dsingleton** [comment]
`government-frontend` has a selection of component asserts now: https://github.com/alphagov/government-frontend/blob/master/test/test_helper.rb#L39-L121 

If this does get standardised that would be a good place to pick from.

**Comment by fofr** [comment]
This has been helpful in `collections` for testing arguments to components:
```ruby
def within_static_component(component)
    within(shared_component_selector(component)) do
      component_args = JSON.parse(page.text).with_indifferent_access
      yield component_args
    end
  end
```

https://github.com/alphagov/collections/blob/61c18b335770a93b154686addca27313aea5737c/test/integration_test_helper.rb#L19-L24

Based on:
https://github.com/alphagov/government-frontend/blob/master/test/test_helper.rb#L91-L96
