### ISSUE TITLE
meta tags are getting added multiple way's across static and slimmer

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/slimmer#195]
We currently are adding meta tags in multiple ways, we should decide on one and stick with it i think. generally recommend to remove from slimmer and use normal templating.

https://github.com/alphagov/static/pull/1006

https://github.com/alphagov/static/blob/e87cdf94a86dba24f9609b980461fbb7386b47d2/app/views/govuk_component/analytics_meta_tags.raw.html.erb

https://github.com/alphagov/slimmer/blob/master/lib/slimmer/processors/metadata_inserter.rb#L15

**Comment by tijmenb** [comment]
This is going to be fixed by retiring static: https://trello.com/c/zLiC5VwG
