### ISSUE TITLE
deprecation warnings

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/slimmer#196]
filters are getting deprecated, i think it's just a [wording change](https://github.com/pboling/cacheable-flash/pull/44/files#diff-9a6ecb55993617bc3ec36628b26b48c7R26) 

https://github.com/alphagov/slimmer/blob/868095a99fdf559cdad80b9102d882322214bc60/lib/slimmer/template.rb#L14

**Comment by fofr** [comment]
Fixed in https://github.com/alphagov/slimmer/pull/209
