### ISSUE TITLE
Webmock only listed as development dependency

### ISSUE THREAD

**Issue by fofr** [alphagov/slimmer#201]
We require webmock in the component test helpers here:
https://github.com/alphagov/slimmer/blob/47631633f1a8e863b889595f87ed22e650c76f01/lib/slimmer/test_helpers/govuk_components.rb#L1

This gets included when a host application loads the slimmer test helpers:
https://github.com/alphagov/slimmer#rspec
https://github.com/alphagov/slimmer/blob/47631633f1a8e863b889595f87ed22e650c76f01/lib/slimmer/rspec.rb#L5

But we only define webmock as a development dependency:
https://github.com/alphagov/slimmer/blob/47631633f1a8e863b889595f87ed22e650c76f01/slimmer.gemspec#L33

A host application without webmock errors with:
```
active_support/dependencies.rb:293:in `require': cannot load such file -- webmock (LoadError)
```

**Comment by tijmenb** [comment]
I suppose this is no longer a problem with the coupling of slimmer and govuk_publishing_components?
