### ISSUE TITLE
Nokogiri deprecation warnings

### ISSUE THREAD

**Issue by KludgeKML** [alphagov/slimmer#283]
Deploying licencefinder, I can see deprecation warnings from Nokogiri called from Slimmer:

`/data/vhost/licencefinder/shared/bundle/ruby/2.7.0/gems/slimmer-16.0.0/lib/slimmer/processors/metadata_inserter.rb:22: warning: Passing a Node as the second parameter to Node.new is deprecated. Please pass a Document instead, or prefer an alternative constructor like Node#add_child. This will become an error in a future release of Nokogiri.`

**Comment by kevindew** [comment]
Looks like this was resolved in https://github.com/alphagov/slimmer/pull/277
